# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-04 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_poll_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='about',
            field=models.TextField(),
        ),
    ]
