# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-04 18:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_auto_20200105_0014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='yt',
            new_name='tv',
        ),
    ]
