# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-04 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_auto_20200105_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='set_name',
            field=models.TextField(default='-'),
        ),
    ]
