# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-04 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_poll_set_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
