# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-04 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0007_auto_20200105_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='about',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='poll',
            name='fb',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='poll',
            name='ln',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='poll',
            name='set_name',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='poll',
            name='tv',
            field=models.CharField(default='-', max_length=30),
        ),
    ]
